wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1657731522
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.10.4
      5: 0.12.21
      8:
      - 3
      - 5
accumulation_steps:
  desc: null
  value: 1
data_args:
  desc: null
  value:
    batch_size: 1
    eval_batch_size: 1
    max_seq_length: 64
    shuffle: true
do_eval:
  desc: null
  value: true
do_eval_on_train:
  desc: null
  value: false
do_test:
  desc: null
  value: false
do_train:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0001
model_args:
  desc: null
  value:
    dropout: 0.5
    lstm_args:
      batch_first: true
      bias: true
      bidirectional: true
      dropout: 0.2
      hidden_size: 256
      input_size: 50
      num_layers: 3
      proj_size: 0
    output_size: 5
name:
  desc: null
  value: debug
num_epochs:
  desc: null
  value: 50
seed:
  desc: null
  value: 42
